### ISSUE TITLE
Delete duplicate files with ~

### ISSUE THREAD

**Issue by mkbehbehani** [tabislick/tabislick#5]
@tabislick 
I'm seeing a bunch of duplicate files with ~ on the end, delete them, move any code over you want into the file without it.

**Comment by tabislick** [comment]
I've checked in app/assets, app/views, and app/controllers but I don't see any in these folders that end in ~. Do you know which folder you saw these in?

**Comment by tabislick** [comment]
Deleted files ending with ~
