### ISSUE TITLE
Improved gitignore

### ISSUE THREAD

**Issue by mkbehbehani** [tabislick/tabislick#6]
Github has a series of recommended gitignores for different languages/frameworks. When starting a new project you'll want to make sure you've got one like this: 

https://github.com/github/gitignore/blob/master/Rails.gitignore

If you don't, you may find heroku rejecting your slug for being too large or all sorts of other odd issues.

**Comment by nelsonblaha** [comment]
Related: #9

**Comment by tabislick** [comment]
Updated .gitignore...not sure I quite get this part, but I'll do some reading on it. Thanks!
