### ISSUE TITLE
Delete duplicate assets

### ISSUE THREAD

**Issue by mkbehbehani** [tabislick/tabislick#7]
@tabislick
Now that you've added cdn jquery and bootstrap, remove their duplicates from the asset pipeline. Delete:
https://github.com/tabislick/tabislick/blob/master/app/assets/javascripts/application.js#L13
and
https://github.com/tabislick/tabislick/blob/master/app/assets/javascripts/application.js#L14

**Comment by tabislick** [comment]
Removed duplicates from asset pipeline!
